import { User, Task, Event } from './types';

export const INITIAL_USERS: User[] = [
  { id: 'usr-admin', name: 'Administrador', color: '#4f46e5', role: 'admin', password: 'admin' },
  { id: 'usr-1', name: 'CDI-128', color: '#ec4899', role: 'user', password: '123' },
  { id: 'usr-2', name: 'CDI-130', color: '#3b82f6', role: 'user', password: '123' },
  { id: 'usr-3', name: 'CDI-135', color: '#10b981', role: 'user', password: '123' },
  { id: 'usr-4', name: 'CDI-201', color: '#f59e0b', role: 'user', password: '123' },
  { id: 'usr-5', name: 'CDI-291', color: '#8b5cf6', role: 'user', password: '123' },
  { id: 'usr-6', name: 'CDI-305', color: '#a855f7', role: 'user', password: '123' },
  { id: 'usr-7', name: 'CDI-387', color: '#f43f5e', role: 'user', password: '123' },
  { id: 'usr-8', name: 'CDI-453', color: '#06b6d4', role: 'user', password: '123' },
  { id: 'usr-9', name: 'CDI-495', color: '#059669', role: 'user', password: '123' },
  { id: 'usr-10', name: 'CDI-529', color: '#ea580c', role: 'user', password: '123' },
  { id: 'usr-11', name: 'CDI-721', color: '#3b82f6', role: 'user', password: '123' },
  { id: 'usr-12', name: 'CDI-845', color: '#10b981', role: 'user', password: '123' },
  { id: 'usr-13', name: 'CDI-863', color: '#8b5cf6', role: 'user', password: '123' },
  { id: 'usr-14', name: 'CDI-864', color: '#f59e0b', role: 'user', password: '123' },
  { id: 'usr-15', name: 'CDI-909', color: '#ec4899', role: 'user', password: '123' },
  { id: 'usr-16', name: 'CDI-910', color: '#06b6d4', role: 'user', password: '123' },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'tsk-1',
    title: 'Diseñar interfaz de usuario principal',
    description: 'Crear los bocetos en alta definición y prototipos interactivos para el dashboard principal en tema claro y oscuro.',
    assigneeId: 'usr-1',
    creatorId: 'usr-3',
    priority: 'Alta',
    status: 'En Progreso',
    dueDate: '2026-06-22',
    category: 'Diseño',
    createdAt: '2026-06-15T10:00:00.000Z',
  },
  {
    id: 'tsk-2',
    title: 'Configurar servidor Express y enrutamiento',
    description: 'Establecer el esqueleto principal del backend para endpoints de la API, middlewares de validación y control de errores.',
    assigneeId: 'usr-2',
    creatorId: 'usr-2',
    priority: 'Alta',
    status: 'Completada',
    dueDate: '2026-06-18',
    category: 'Backend',
    createdAt: '2026-06-14T09:00:00.000Z',
  },
  {
    id: 'tsk-3',
    title: 'Crear suite de pruebas automatizadas',
    description: 'Definir casos de uso de prueba para validaciones de usuarios, flujos lógicos y carga/descarga de archivos JSON.',
    assigneeId: 'usr-3',
    creatorId: 'usr-2',
    priority: 'Baja',
    status: 'Pendiente',
    dueDate: '2026-06-30',
    category: 'QA / Testing',
    createdAt: '2026-06-16T14:30:00.000Z',
  },
  {
    id: 'tsk-4',
    title: 'Optimización de assets y carga perezosa',
    description: 'Comprimir todas las imágenes, habilitar compresión gzip/brotli y modularizar componentes pesados para un rendimiento superior.',
    assigneeId: 'usr-1',
    creatorId: 'usr-3',
    priority: 'Media',
    status: 'Completada',
    dueDate: '2026-06-19',
    category: 'Frontend',
    createdAt: '2026-06-15T11:20:00.000Z',
  },
  {
    id: 'tsk-5',
    title: 'Definición de requerimientos con el cliente',
    description: 'Reunión kickoff para pulir la lista de funcionalidades de la fase 1, definir el alcance del proyecto y fechas límite.',
    assigneeId: 'usr-3',
    creatorId: 'usr-1',
    priority: 'Alta',
    status: 'Completada',
    dueDate: '2026-06-12',
    category: 'Gestión',
    createdAt: '2026-06-10T08:00:00.000Z',
  },
  {
    id: 'tsk-6',
    title: 'Preparar despliegue en ambiente Cloud Run',
    description: 'Escribir el Dockerfile multi-etapa, configurar variables de entorno para producción y validar los puertos de enlace.',
    assigneeId: 'usr-4',
    creatorId: 'usr-2',
    priority: 'Alta',
    status: 'Pendiente',
    dueDate: '2026-06-25',
    category: 'DevOps',
    createdAt: '2026-06-18T16:00:00.000Z',
  },
  {
    id: 'tsk-7',
    title: 'Actualizar documentación técnica e instructivos',
    description: 'Escribir manuales detallados de la arquitectura del software, flujos lógicos e instructivos para nuevos desarrolladores.',
    assigneeId: 'usr-2',
    creatorId: 'usr-1',
    priority: 'Baja',
    status: 'En Progreso',
    dueDate: '2026-06-28',
    category: 'Documentación',
    createdAt: '2026-06-17T11:00:00.000Z',
  },
  {
    id: 'tsk-8',
    title: 'Revisión técnica de accesibilidad (a11y)',
    description: 'Comprobar el contraste de colores, navegación por teclado, uso de etiquetas ARIA y compatibilidad con lectores de pantalla.',
    assigneeId: 'usr-1',
    creatorId: 'usr-1',
    priority: 'Media',
    status: 'Pendiente',
    dueDate: '2026-06-26',
    category: 'Frontend',
    createdAt: '2026-06-18T10:00:00.000Z',
  },
  {
    id: 'tsk-9',
    title: 'Corregir fallos de rendimiento en móviles',
    description: 'Investigar cuellos de botella en dispositivos móviles de gama baja y reducir las re-renderizaciones innecesarias.',
    assigneeId: 'usr-3',
    creatorId: 'usr-4',
    priority: 'Media',
    status: 'Completada',
    dueDate: '2026-06-17',
    category: 'QA / Testing',
    createdAt: '2026-06-14T15:00:00.000Z',
  },
];

export const INITIAL_EVENTS: Event[] = [
  {
    id: 'evt-1',
    title: 'Planificación de Sprint #4',
    date: '2026-06-22',
    time: '10:00',
    description: 'Definición del backlog del próximo sprint de dos semanas, compromisos del equipo y asignación inicial de deudas técnicas.',
    participantIds: ['usr-1', 'usr-2', 'usr-3', 'usr-4'],
    creatorId: 'usr-1',
    createdAt: '2026-06-15T09:00:00.000Z',
  },
  {
    id: 'evt-2',
    title: 'Revisión Técnica de Arquitectura',
    date: '2026-06-24',
    time: '14:30',
    description: 'Presentación y discusión sobre la estructura de datos propuesta, optimización de solicitudes SQL y mitigación de latencias.',
    participantIds: ['usr-2', 'usr-3'],
    creatorId: 'usr-2',
    createdAt: '2026-06-16T12:00:00.000Z',
  },
  {
    id: 'evt-3',
    title: 'Reunión de Demostración de Avances',
    date: '2026-06-29',
    time: '16:00',
    description: 'Demostración en vivo de las funcionalidades completadas para recopilar retroalimentación de las áreas involucradas.',
    participantIds: ['usr-1', 'usr-2', 'usr-3', 'usr-4'],
    creatorId: 'usr-1',
    createdAt: '2026-06-18T08:00:00.000Z',
  },
  {
    id: 'evt-4',
    title: 'Sesión Creativa y Lluvia de Ideas',
    date: '2026-06-18',
    time: '11:00',
    description: 'Reunión para explorar propuestas de diseño visual de la marca, paletas cromáticas secundarias y transiciones dinámicas.',
    participantIds: ['usr-1', 'usr-4'],
    creatorId: 'usr-1',
    createdAt: '2026-06-14T14:00:00.000Z',
  },
  {
    id: 'evt-5',
    title: 'Daily Standup Almuerzo Informativo',
    date: '2026-06-20',
    time: '12:30',
    description: 'Sincronización diaria rápida para resolver impedimentos del equipo de trabajo y planificar el fin de semana de guardias.',
    participantIds: ['usr-1', 'usr-2', 'usr-3', 'usr-4'],
    creatorId: 'usr-3',
    createdAt: '2026-06-19T08:30:00.000Z',
  },
];
